/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tpalucki' at '07.04.17 14:01' with Gradle 2.10
 *
 * @author tpalucki, @date 07.04.17 14:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
