import org.junit.Test;
import pl.advancewars.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'tpalucki' at '07.04.17 14:01' with Gradle 2.10
 *
 * @author tpalucki, @date 07.04.17 14:01
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
